### ISSUE TITLE
Add support for FileProvider

### ISSUE THREAD

**Issue by LucasGGamerM** [grishka/LiteX#1]
I have been working on a fork of the official mastodon for android app, and to allow creation of camera shortcut, I need this class to allow me to share an Uri outside the app, to then write an image to it and then share it. 

AndroidX has it, but Appkit doesn't

**Comment by grishka** [comment]
You probably meant to create this in the LiteX repo but ok, request taken

**Comment by LucasGGamerM** [comment]
Thank you. I shall be waiting then

**Comment by grishka** [comment]
Actually, FileProvider is a very much self-contained class. It's also part of `androidx.core`, not a separate library like I thought it was. It also doesn't use much from AndroidX. See for yourself: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/content/FileProvider.java

It feels kinda pointless to create an entirely new library for just one class. To make it work without the rest of AndroidX, you need to add the source to your project and make just two changes:
- Replace all occurrences of `ResourcesCompat.ID_NULL` with `0`
- Replace `ContextCompat.getXXX(context, ...)` with `context.getXXX(...)`

**Comment by LucasGGamerM** [comment]
Thank you! It works!
